### ISSUE TITLE
Dear professor wilselby, when do you start to write the documentation on how to set it up and use it

### ISSUE THREAD

**Issue by ouyangandy** [wilselby/diy_driverless_car_ROS#1]

**Comment by wilselby** [comment]
All my documentation is at:

https://www.wilselby.com/research/autonomous-vehicles/diy-autonomous-vehicle-project/

Wil Selby
www.wilselby.com <http://wilselby.com>
LinkedIn <https://www.linkedin.com/in/wilselby/> | YouTube
<https://www.youtube.com/user/wilSelby>
