### ISSUE TITLE
odom frame does not exist

### ISSUE THREAD

**Issue by mvgianel** [wilselby/diy_driverless_car_ROS#5]
I am not very familiar with ROS, and I am trying to understand how to simulate a robot and do mapping with a LiDar and cartographer in ROS. I would like to be able to visualize a point cloud and read messages from the imu topic.

I am trying to run the following command: roslaunch rover_gazebo rc_dbw_walker.launch rviz:=true world_name:=willowgarage teb:=true frontier:=true x:=-0.4 y:=5.5 yaw:=1.5 gui:=false 

But when I do, I get the following error:  [ERROR] [1595493283.292215429]: gazebo_ros_p3d plugin: frameName: odom does not exist, will not publish pose

![Screenshot from 2020-07-23 04-22-49](https://user-images.githubusercontent.com/23347523/88267553-ff661280-cc9e-11ea-893a-d30a32a5f3c8.png)

I found that if I change the Fixed Frame from odom to base_link in the rc_model.rviz file, I am able to visualize the model and pointcloud on rviz. However, I realized that no imu messages are being published.

![Screenshot from 2020-07-23 03-41-58](https://user-images.githubusercontent.com/23347523/88267818-64ba0380-cc9f-11ea-96c0-fdd9224c2423.png)

What do I need to do to visualize the lidar and imu data?

**Comment by changpowei** [comment]
Hi @mvgianel, 

I'm facing same problem with you! Did you figure out how to solve this?

**Comment by mvgianel** [comment]
Hello @changpowei,

I solved this issue some time ago, so I am not 100% sure, but I believe the problem was that I was missing the hector-gazebo plugins. This is the wiki for them [http://wiki.ros.org/hector_gazebo_plugins](url). You can probably install them with "sudo apt-get install ros-melodic-hector-gazebo-plugins" but I am not sure. 

Hope that helps!
